general:
  #Determines how many second CCL will wait before considering the server finished loading. If you have a warning in the console or registry issues, try increasing this value
  postWorldLoadTime: 3
  #Fix a custom item rename issue by disabling the ability to rename custom items in an anvil
  fixAnvil: true

customTextures:
  #View radius of custom textures in chunks
  viewRadius: 6
  #Update period of custom textures in ticks
  updatePeriod: 20
  #Hide blocks that are surrounded by other blocks
  occluding: true

integrations:
  #Enable WorldEdit integration for custom blocks (Very slow with FastAsyncWorldEdit)
  worldEdit: false

#Debugging tool, you can disable here every listener independently
features:
  customItems: true
  customArmors: true
  customBlocks: true
  customRecipes: true