name: CustomContentLib
version: 1.3.1
author: VadamDev
description: CustomContentLib is a VIAPI extension that helps the creation of new items/blocks/etc for Minecraft 1.8
website: https://github.com/VadamDev/CustomContentLib

depend: [VIAPI]
softdepend: [WorldEdit, FastAsyncWorldEdit]
main: net.vadamdev.customcontent.internal.CustomContentPlugin